{{- if not .Values.proxyAPIKeySecret.external -}}
{{- if .Values.proxyAPIKeySecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spotify-auth-proxy.proxyAPIKeySecretName" . }}
  labels:
    {{- include "spotify-auth-proxy.labels" . | nindent 4 }}
  {{- with .Values.proxyAPIKeySecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  spotifyProxyAPIKey: {{ .Values.proxyAPIKeySecret.spotifyProxyAPIKey | b64enc }}
{{- end }}
{{- end }}
