{{- if .Values.clientCredentialsSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spotify-auth-proxy.clientCredentialsSecretName" . }}
  labels:
    {{- include "spotify-auth-proxy.labels" . | nindent 4 }}
  {{- with .Values.clientCredentialsSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  spotifyClientID: {{ .Values.clientCredentialsSecret.spotifyClientID | b64enc }}
  spotifyClientSecret: {{ .Values.clientCredentialsSecret.spotifyClientSecret | b64enc }}
{{- end }}
