apiVersion: v1
kind: Service
metadata:
  name: {{ include "spotify-auth-proxy.fullname" . }}
  labels:
    {{- include "spotify-auth-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 27228
      protocol: TCP
      name: callback
  selector:
    {{- include "spotify-auth-proxy.selectorLabels" . | nindent 4 }}
